name: Release - SampSharp

on:
  push:
    branches:
      - build
    tags:
      - '1.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Build open.mp component
        run: .\build.cmd component publish

      - name: Upload Windows component
        uses: actions/upload-artifact@v7
        with:
          name: component-windows
          path: build/artifacts/sampsharp-component/
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc g++ cmake

      - name: Build open.mp component
        run: ./build.sh component publish

      - name: Upload Linux component
        uses: actions/upload-artifact@v7
        with:
          name: component-linux
          path: build/artifacts/sampsharp-component/
          if-no-files-found: error